require 'rake'
files = Rake::FileList["**/*.md", "**/*.markdown"]
files.exclude("~*")
files.exclude(/^scratch\//)
files # => ["ch1.md", "ch2.md", "ch3.md", "scratch/test.md", "subdir/appendix.md", "temp.md", "~ch1.md", "ch4.markdown"]

